/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Control.controlRol;
import Control.controlUsuario;
import java.awt.HeadlessException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author David JP
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaPrincipal
     */
    
    controlUsuario cu = new Control.controlUsuario();
    controlRol cr = new Control.controlRol();
    DefaultTableModel dtm;
    DefaultComboBoxModel cbx;
    
    String nombresColumnas[] = {"Id Usuario", "Id rol", "Nombre", "Activo"};
    
    public VistaPrincipal() {
        
        Object[][] data = cu.consultarUsuarios();        
        dtm = new DefaultTableModel(data, nombresColumnas);      
        
        Object[][] roles = cr.consultarRoles();

        int num_roles = cr.contarRoles();
        int i = 0;
        String aux[] = new String[num_roles];

        while (i != num_roles) {

            aux[i] = String.valueOf(roles[i][0] + "-" + roles[i][1]);

            i++;

        }

        cbx = new DefaultComboBoxModel(aux);
        
        initComponents();
                       
        tblusuarios.setModel(dtm);
        
        panelInfoUsuario.setVisible(false);
        idins.setVisible(false);
        lbltxtidins.setVisible(false);
        txtnumregistros.setText(String.valueOf(data.length));
    }    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public int Conseguir_cod_rol() {
            int aux = cbxroles.getSelectedItem().toString().indexOf("-");
            //Object data[][] = ca.consultarCategoriaNombre(cbxcategoria.getSelectedItem().toString().substring(aux + 1, cbxcategoria.getSelectedItem().toString().length()));;

            String cadena = String.valueOf(cbxroles.getSelectedItem().toString().substring(0, aux));
            int numero = Integer.parseInt(cadena);
            return numero;
        }
    
        public void actualizarTabla() {
            
        Object[][] data = cu.consultarUsuarios();        
        dtm = new DefaultTableModel(data, nombresColumnas);
                
        tblusuarios.setModel(dtm);       
        
        txtnumregistros.setText(String.valueOf(data.length));
        }
        
        public void limpiar(){
            txtnombre.setText("");
           cbxroles.setSelectedIndex(0);
           
         int numberid = cu.obtenerMaxidUsuario();
        idins.setText(String.valueOf(numberid + 1));
        
        rdbsi.setSelected(true);
        rdbno.setSelected(false);
        }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnconsultar = new javax.swing.JButton();
        btnlimpiar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        txtnombreconsulta = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btncrear = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblusuarios = new javax.swing.JTable();
        txtnumregistros = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        panelInfoUsuario = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnguardar = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        btneditar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        lbltxtidins = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        rdbsi = new javax.swing.JRadioButton();
        rdbno = new javax.swing.JRadioButton();
        cbxroles = new javax.swing.JComboBox<>();
        txtnombre = new javax.swing.JTextField();
        idins = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setBackground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("Parametros de Busqueda");

        btnconsultar.setText("Consultar");
        btnconsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconsultarActionPerformed(evt);
            }
        });

        btnlimpiar.setText("Limpiar");
        btnlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiarActionPerformed(evt);
            }
        });

        jLabel3.setText("Nombre: ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnconsultar)
                        .addGap(18, 18, 18)
                        .addComponent(btnlimpiar)
                        .addContainerGap(355, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtnombreconsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(4, 4, 4)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnconsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnlimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtnombreconsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 20, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        jLabel2.setBackground(new java.awt.Color(0, 51, 255));
        jLabel2.setText("Lista de Usuarios");

        btncrear.setText("Crear");
        btncrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncrearActionPerformed(evt);
            }
        });

        tblusuarios.setModel(dtm);
        tblusuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblusuariosMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblusuarios);

        txtnumregistros.setText("0");

        jLabel4.setText("Total Registros: ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btncrear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtnumregistros, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btncrear, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnumregistros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelInfoUsuario.setBackground(new java.awt.Color(204, 204, 255));

        jLabel5.setBackground(new java.awt.Color(0, 51, 255));
        jLabel5.setText("Información de Usuario");

        btnguardar.setText("Guardar");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        btneditar.setText("Editar");
        btneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditarActionPerformed(evt);
            }
        });

        btneliminar.setText("Eliminar");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        lbltxtidins.setText("id");

        jLabel7.setText("nombre");

        jLabel8.setText("Rol");

        jLabel9.setText("Activo");

        rdbsi.setSelected(true);
        rdbsi.setText("Si");
        rdbsi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdbsiMouseClicked(evt);
            }
        });

        rdbno.setText("No");
        rdbno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdbnoMouseClicked(evt);
            }
        });

        cbxroles.setModel(cbx);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(lbltxtidins))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtnombre, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                            .addComponent(idins)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(rdbsi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rdbno))
                            .addComponent(cbxroles, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltxtidins)
                    .addComponent(idins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cbxroles, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(rdbsi)
                    .addComponent(rdbno))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelInfoUsuarioLayout = new javax.swing.GroupLayout(panelInfoUsuario);
        panelInfoUsuario.setLayout(panelInfoUsuarioLayout);
        panelInfoUsuarioLayout.setHorizontalGroup(
            panelInfoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInfoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInfoUsuarioLayout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jSeparator4)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
                    .addGroup(panelInfoUsuarioLayout.createSequentialGroup()
                        .addComponent(btnguardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btneditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btneliminar)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        panelInfoUsuarioLayout.setVerticalGroup(
            panelInfoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoUsuarioLayout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(4, 4, 4)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInfoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btneditar, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelInfoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelInfoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Gestión de Usuarios", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnconsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsultarActionPerformed
        panelInfoUsuario.setVisible(false);
        
        Object data[][];
        data = cu.consultarUsuarioNombre(txtnombreconsulta.getText());
        dtm = new DefaultTableModel(data, nombresColumnas);     
        tblusuarios.setModel(dtm);
    }//GEN-LAST:event_btnconsultarActionPerformed

    private void btncrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncrearActionPerformed
        txtnombre.setText("");
        cbxroles.setSelectedIndex(0);
        
        panelInfoUsuario.setVisible(true);
        btneditar.setEnabled(false);
        btneliminar.setEnabled(false);
        btnguardar.setEnabled(true);
        idins.setEnabled(false);
        
        rdbno.setSelected(false);
        rdbsi.setSelected(true);
        
        int numberid = cu.obtenerMaxidUsuario();
        idins.setText(String.valueOf(numberid + 1));
        
    }//GEN-LAST:event_btncrearActionPerformed

    private void btnlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiarActionPerformed
        // TODO add your handling code here:
        Object[][] data = cu.consultarUsuarios();        
        dtm = new DefaultTableModel(data, nombresColumnas); 
        tblusuarios.setModel(dtm);
        
        txtnombreconsulta.setText("");
        panelInfoUsuario.setVisible(false);
    }//GEN-LAST:event_btnlimpiarActionPerformed

    private void rdbsiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdbsiMouseClicked
        // TODO add your handling code here:
        if (rdbno.isSelected()) {
            rdbno.setSelected(false);
        }
    }//GEN-LAST:event_rdbsiMouseClicked

    private void rdbnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdbnoMouseClicked
        // TODO add your handling code here:
        if (rdbsi.isSelected()) {
            rdbsi.setSelected(false);
        }
    }//GEN-LAST:event_rdbnoMouseClicked

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        // TODO add your handling code here:
        String nombre = txtnombre.getText();
        int id_rol = Conseguir_cod_rol();
        String activo = "0";
        if (rdbsi.isSelected()) {
            activo = "1";
        }else if(rdbno.isSelected()){
            activo = "0";
        }
        
        int num_coincidencia= 0;
        num_coincidencia = cu.consultarUsuarioNombre_identico(txtnombre.getText());
        
        if(num_coincidencia >= 1){
             JOptionPane.showMessageDialog(this, "El registro NO se ha guardado\nEl nombre ya existe!", "Error", JOptionPane.ERROR_MESSAGE);
        }else{
            
            boolean inserto = cu.insertarUsuario(id_rol,nombre,activo);
                if (inserto) {
                    JOptionPane.showMessageDialog(this, "Guardado Exitosamente!", "Confirmacion", JOptionPane.INFORMATION_MESSAGE);
                    actualizarTabla();
                    limpiar();
                } else {
                    JOptionPane.showMessageDialog(this, "El registro NO se ha guardado Corrrectamente\nRevise los datos Ingresados!", "Confirmacion", JOptionPane.ERROR_MESSAGE);
                }
        }
    }//GEN-LAST:event_btnguardarActionPerformed

    private void tblusuariosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblusuariosMousePressed
        // TODO add your handling code here:
        int filaseleccionada;
        
        idins.setEnabled(false);
        
        btneditar.setEnabled(true);        
        btneliminar.setEnabled(true);
        
        DefaultTableModel modelotabla=(DefaultTableModel) tblusuarios.getModel();
            try{
                filaseleccionada= tblusuarios.getSelectedRow();
                if (filaseleccionada==-1 || modelotabla.getValueAt(filaseleccionada, 0)==null){
                    JOptionPane.showMessageDialog(null, "Elija un usuario");
                    idins.setText("");
                    txtnombre.setText("");
                    cbxroles.setSelectedIndex(0);
                    rdbsi.setSelected(false);
                    rdbno.setSelected(false);
                    
                }else{
                    idins.setText(String.valueOf(modelotabla.getValueAt(filaseleccionada, 0)));
                    cbxroles.setSelectedItem(String.valueOf(modelotabla.getValueAt(filaseleccionada, 1)));
                    txtnombre.setText((String) modelotabla.getValueAt(filaseleccionada, 2));                    
                    if (String.valueOf(modelotabla.getValueAt(filaseleccionada, 3)).equals("1-Activo")) {
                        rdbsi.setSelected(true);
                        rdbno.setSelected(false);
                    }else if(String.valueOf(modelotabla.getValueAt(filaseleccionada, 3)).equals("0-Inactivo")){
                        rdbno.setSelected(true);
                        rdbsi.setSelected(false);
                    }
                    btnguardar.setEnabled(false);
                  panelInfoUsuario.setVisible(true);
                }
            }catch (HeadlessException ex){
                  JOptionPane.showMessageDialog(null, "Error: "+ex+"\nInténtelo nuevamente", " .::Error En la Operacion::." ,JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_tblusuariosMousePressed

    private void btneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditarActionPerformed
        String nombre = txtnombre.getText();
        int id_rol = Conseguir_cod_rol();
        int id = Integer.parseInt(idins.getText());
        
        
        String activo = "0";
        if (rdbsi.isSelected()) {
            activo = "1";
        }else if(rdbno.isSelected()){
            activo = "0";
        }
        //actualizarUsuario
        int num_coincidencia= 0;
        num_coincidencia = cu.consultarUsuarioNombre_identico(nombre);
        
        if(num_coincidencia > 1){
            JOptionPane.showMessageDialog(this, "El registro NO se ha Actualizado\nEl nombre ya existe, intente con otro nombre!", "Error", JOptionPane.ERROR_MESSAGE);
        }else{
            boolean actualizo = cu.actualizarUsuario(id,id_rol,nombre,activo);
                   if (actualizo) {
                       JOptionPane.showMessageDialog(this, "Actualizado Exitosamente!", "Confirmacion", JOptionPane.INFORMATION_MESSAGE);
                       actualizarTabla();                    
                   } else {
                       JOptionPane.showMessageDialog(this, "El registro NO se ha actualizado \nRevise los datos Ingresados!", "Confirmacion", JOptionPane.ERROR_MESSAGE);
                   }
        }
    }//GEN-LAST:event_btneditarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        // TODO add your handling code here:        

            if (!idins.getText().isEmpty()) {                                    

                    int res = JOptionPane.showConfirmDialog(this, "Seguro que desea eliminar el registro del usuario: " + txtnombre.getText() + " ?", "Confirmacion", JOptionPane.WARNING_MESSAGE);
                    if (res == JOptionPane.YES_OPTION) {
                        
                        if(cu.eliminarUsuario(Integer.parseInt(idins.getText()))){
                          JOptionPane.showMessageDialog(this, "Eliminado!", "confirmacion!", JOptionPane.INFORMATION_MESSAGE);  
                          limpiar();
                          actualizarTabla();
                          panelInfoUsuario.setVisible(false);
                        }else{
                            JOptionPane.showMessageDialog(this, "Ocurrio un problema al eliminar!", "confirmacion!", JOptionPane.INFORMATION_MESSAGE);
                            panelInfoUsuario.setVisible(false);
                        }                                               
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "NO se encontro el registro!", "confirmacion!", JOptionPane.INFORMATION_MESSAGE);
                    panelInfoUsuario.setVisible(false);
                }            

        
    }//GEN-LAST:event_btneliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrincipal().setVisible(true);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnconsultar;
    private javax.swing.JButton btncrear;
    private javax.swing.JButton btneditar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnlimpiar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cbxroles;
    private javax.swing.JTextField idins;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbltxtidins;
    private javax.swing.JPanel panelInfoUsuario;
    private javax.swing.JRadioButton rdbno;
    private javax.swing.JRadioButton rdbsi;
    private javax.swing.JTable tblusuarios;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtnombreconsulta;
    private javax.swing.JLabel txtnumregistros;
    // End of variables declaration//GEN-END:variables
}
